### ISSUE TITLE
Feature request:  better handling for deleted help messages.

### ISSUE THREAD

**Issue by JasonRajtar** [PuzzleServer/mainpuzzleserver#1061]
I've had some teams put in a help request, but when I go to the thread list, it's not there.  I have the email and the notification, but it's confusing when I can't find a thread.  We're assuming this is because the team has decided to delete their message, but it might be nice if it showed on the list as deleted so that can match it up to the notification I got.

**Comment by vidapour** [comment]
unsend messages
