### ISSUE TITLE
Feature request: ability to see puzzle authors from help thread list.

### ISSUE THREAD

**Issue by JasonRajtar** [PuzzleServer/mainpuzzleserver#1062]
I see help threads coming in and I want to let the author know that they have a help request, but I don't know who the authors are.  When I click on the puzzle link, I just get an access denied since I'm not the author.  It would be nice if I could easily see who to notify.

**Comment by jbodner09** [comment]
Sortable headers would also be super helpful.

**Comment by vidapour** [comment]
done with #1108
