### ISSUE TITLE
Implement area specific auth

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#14]
- dependent on overall auth first
- site owners can access everything everything (if possible, add blocking specific puzzle content so that site owners can have full tech control without content access)
- event owners can access everything related to the event (owner perms are a superset of author perms)
- authors can only access their own puzzles, but can add new puzzles, as well as do all editing on their puzzles (including file upload & unlock mechanisms) (authors perms are a superset of players)
- players can only access puzzles that have been unlocked for their team, team details, their profile, etc

**Comment by jenetlan** [comment]
https://github.com/PuzzleServer/mainpuzzleserver/pull/278
