### ISSUE TITLE
[P0] Change t-shirt size to a dropdown

### ISSUE THREAD

**Issue by lambertwang** [PuzzleServer/mainpuzzleserver#154]
This is a low priority issue.

**Comment by jenetlan** [comment]
Given that this is a key usability item for participants and could save us a lot of headache in sorting through sizes, I'm upgrading this to a P1

**Comment by jenetlan** [comment]
Removing from Jan since I think this will be much easier once https://github.com/PuzzleServer/mainpuzzleserver/issues/184 is completed.

**Comment by jenetlan** [comment]
Completed by https://github.com/PuzzleServer/mainpuzzleserver/pull/407
