### ISSUE TITLE
Add PuzzleUser view / edit page (not create or delete)

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#184]
Players and Admins should be able to view and edit some PuzzleUser properties. Specifically:

- Name
- EmployeeAlias
- PhoneNumber
- TShirtSize
- VisibleToOthers

This page should be linked from each row in the /Events/Players page for admins and it should probably be its own item in the navigation header for now (you can talk to Megan about whether or not it should be added to the other user properties but we can always do that later)

**Comment by tabascq** [comment]
Addressed with #240
