### ISSUE TITLE
Role-switcher should only show roles the user has access to

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#185]
In the /Shared/_RoleSwitcherPartial.cshtml file, right now the dropdown always includes every possible role. However, some users may not have access to author or admin roles, in which case they should not be included in the dropdown. Especially for players, the dropdown doesn't even need to exist (although the page title still should).

Kenny suggested adding IsEventAuthor and IsEventAdmin methods to the EventSpecificPageModel (similar to IsRegisteredUser) to help with this.

If it helps to move the dropdown label (the "Event name - Admin / Author" part) into the _RoleSwitcherPartial.cshtml file, feel free to do so :)

**Comment by tabascq** [comment]
Addressed with #232.
