### ISSUE TITLE
Reduce cost / auto-unlock basic hints when advanced hints are purchased

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#204]
Hints might have overlapping information. For example:
- Hint 1: The lines form geometric shapes
- Hint 2: The geometric shapes match country flags
By the time the user unlocks hint 2, hint 1 would be redundant.

The ask is to enable a system where unlocking hint 2 automatically unlocks hint 1 or makes it free. There is also a request where when you unlock hint 1, hint 2 becomes cheaper to reflect the cost overlap.

**Comment by tabascq** [comment]
Fixed by #334
