### ISSUE TITLE
Nav bar covers top of page when resized

### ISSUE THREAD

**Issue by digit01Wave** [PuzzleServer/mainpuzzleserver#210]
When the nav bar gets resized, sometimes it goes to 2 or three lines, causing it to cover the top portion of the current page. 

Note: If it gets resized passed 767px, it collapses into a hamburger menu, which solves the problem.

**Comment by jaylorch** [comment]
This issue has returned.  As a consequence, the top of the page is covered when viewed on an iPad or iPhone.
