### ISSUE TITLE
Shortcuts menu doesn't drop down on Firefox

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#242]
While the shortcuts menu in the grid view is a dropdown in Edge and Chrome, Firefox treats it as always open and as a "Jump To..." link that doesn't go anywhere.

**Comment by morganbr** [comment]
@jenetlan, this might be of interest to you

**Comment by jbodner09** [comment]
Closing as no repro either due to it being fixed over the past few years or it being a browser bug that's been fixed.
