### ISSUE TITLE
[P0] Improved team name checks

### ISSUE THREAD

**Issue by lambertwang-zz** [PuzzleServer/mainpuzzleserver#253]
See title.

**Comment by jenetlan** [comment]
Also require team name to be non-empty

Also this PR was an attempt at this but it wasn't finished - can be used for reference https://github.com/PuzzleServer/mainpuzzleserver/pull/281

**Comment by jenetlan** [comment]
List of checks:
* Enforce unique team names
* Require team name to be printable (non-whitespace, maybe special characters? idk)
* Check for drop table team names / SQL injection team names

**Comment by morganbr** [comment]
#446 required non null/empty/whitespace names and we've confirmed sql injection isn't possible. We still should limit lengths and possibly characters.

**Comment by jbodner09** [comment]
Closing in favor of #763 which will do the length checks.
