### ISSUE TITLE
Responses shouldn't have identical text for the same puzzle

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#255]
Right now, authors/admins can create multiple responses with the same text. This is bad. Please disallow that.

**Comment by tabascq** [comment]
We should absolutely allow multiple responses to have the same ResponseText. If this is about SubmittedText, agree that should be unique per puzzle.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
