### ISSUE TITLE
On the play page, show the answer rather than the solve time

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#272]
We received a suggestion that the puzzle answer was more helpful than the solve time and could replace it on the play page. A potential concern would be if people want to solve puzzles later that they didn't get a chance to see during an event but are spoiled because they've inadvertently seen the answers already.

**Comment by digit01Wave** [comment]
We just agreed to have a separate page that shows all the answers of solved puzzles

**Comment by jenetlan** [comment]
Done https://github.com/PuzzleServer/mainpuzzleserver/pull/353/files
