### ISSUE TITLE
Redirect from login not working

### ISSUE THREAD

**Issue by jaylorch** [PuzzleServer/mainpuzzleserver#327]
When I do the following, it doesn't redirect me properly after login:

1) Go to puzzlehunt.azurewebsites.net/ph20beta/author
2) When prompted, enter username, then password, then authentication token

On my iPhone and iPad, it then directs me to a page that says I need to login (making me think I'd entered my authentication token wrong, when I didn't).  On Chrome on my Mac, it directs me to https://puzzlehunt.azurewebsites.net/.

In both cases, the correct behavior should be to send me to puzzlehunt.azurewebsites.net/ph20beta/author after login.  Instead, I have to type that URL into the address bar manually.

**Comment by jaylorch** [comment]
My teammate says that she experienced this with the join-team page as well (https://puzzlehunt.azurewebsites.net/ph20/play/Teams/Apply?teamId=27).  She went to this URL, she logged in, and it looped her back to the login page.  She had to manually re-enter the URL after logging in to get to it.

**Comment by jbodner09** [comment]
Should be addressed by #785
