### ISSUE TITLE
Performance issues when getting puzzle url

### ISSUE THREAD

**Issue by asyasky** [PuzzleServer/mainpuzzleserver#332]
There's a separate SQL query to get the url for each puzzle displayed on the play & author puzzle pages. Need to use some sort of special object to do a single join and then populate the layout from there.

SELECT [e].[ID], [e].[EventID], [e].[FileType], [e].[PuzzleID], [e].[ShortName], [e].[UrlString] FROM [ContentFiles] AS [e] WHERE [e].[PuzzleID] = @__get_Item_0

**Comment by tabascq** [comment]
Fixed by #351
