### ISSUE TITLE
Submission lockout too permissive

### ISSUE THREAD

**Issue by jaylorch** [PuzzleServer/mainpuzzleserver#344]
In the sandbox, I was able to spam 11 submissions and only got delayed once (by two minutes after the sixth incorrect answer).  This is far too permissive.  I suggest the following algorithm:

If the number of incorrect submissions so far is N, and N>=5, then compute MinimumAllowableSubmitTime = TimeOfLastIncorrectSubmission + Max(5, N-4) minutes.  Don't allow submissions until the current time is MinimumAllowableSubmitTime.

**Comment by tabascq** [comment]
Can we play with the properties in Event Settings that govern this before making this into a coding task?

**Comment by tabascq** [comment]
Fixed by altering timeout settings. No code changes required.
