### ISSUE TITLE
Page for verifying employee aliases

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#361]
We need an admin page that shows the employee aliases grouped by team so that we can manually verify that teams are able to run in Puzzle Hunt.

**Comment by jenetlan** [comment]
![image](https://user-images.githubusercontent.com/22335375/59399115-b4fa2e80-8d47-11e9-8101-d7ccf67a2519.png)

**Comment by jenetlan** [comment]
https://github.com/PuzzleServer/mainpuzzleserver/pull/494 < waiting for this one
