### ISSUE TITLE
Validate email addresses on team and profile page save

### ISSUE THREAD

**Issue by Vroo** [PuzzleServer/mainpuzzleserver#369]
Do not let people save the team or profile page with an invalid email address. Allow multiple email addresses separated by commas or semicolons.

When we send email, we have to silently drop any invalid addresses (since there's no way to notify them that their email address is bad of course). So let's prevent it up front.

**Comment by jbodner09** [comment]
Closing in favor of #763 and since the work to validate team email addresses and allow multiple appears to already be done.
