### ISSUE TITLE
Performance issue (3 second load times) on /Teams/Answers

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#376]
This looks like another join issue - too many roundtrips to the SQL server when the page should be doing a single request with a join.

_MS.ProcessedByMetricExtractors: (Name:'Requests', Ver:'1.0')
Account Id: <undefined>
Application version: 1.0.0.0
AspNetCoreEnvironment: Production
Auth user Id: <undefined>
Browser version: <not collected>
City: Cambridge
Client IP address: 0.0.0.0
Cloud role instance: RD0003FFE533C6
Cloud role name: puzzlehunt
Country or region: United States
Device model: <undefined>
Device type: PC
Event time: 4/7/2019, 1:12:18 PM
Operating system: <not collected>
Operation Id: f344b7c1-46c7920e0b421245
Operation name: GET /Teams/Answers
Parent Id: f344b7c1-46c7920e0b421245
Request Id: |f344b7c1-46c7920e0b421245.
Request name: GET /Teams/Answers
Request source: <undefined>
Request URL: https://puzzlehunt.azurewebsites.net/1/play/Teams/91/Answers
Response code: 200
Response time: 4.19 s
Sample Rate: 25
SDK version: aspnet5c:2.3.0
Session Id: Cpbwd
Source of synthetic traffic: <undefined>
State or province: Massachusetts
Successful request: true
Telemetry type: request
User Id: EPsyw

<a href="https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/H4sIAAAAAAAAA1VQy26DMBD8lz3jCmMHbK49VFx6aKMeeqkMXhJUsOli95GIf69RElW9rWZnZmfnDJ13gUwXXpCWwTuogUOW0Gn2Dl1oLNRneDQTps0cT6cRj9GFRHmO7dLRMIek2ljQazSmtIIZbCWT2AqmZW5ZaZTkXMqq4Luke8LFR%2BrwgXyc%2F5m%2B0QHWDPyMZG6uLo5jBvh5jQKKW95bIdhOV5xxjprpSkhWVUroVtlelRaugr1pxy024UfEJSwJD8OUJjNth4uca5ZLllf7Iq95UXN1Vwj1eqXdp2LwO9widKY74l8iwh6JkLZ2ws%2BczogM3KWmL0%2FvTcCpSQaHyyuwrr8DqOVnawEAAA%3D%3D/ComponentId/%7B%22Name%22%3A%22puzzlehunt%22%2C%22SubscriptionId%22%3A%22f9eaa6d3-aeb4-4eb3-940d-6a8411447215%22%2C%22ResourceGroup%22%3A%22puzzlehunt_rg%22%7D" target="_blank">View this instance in the Azure portal<\a>

**Comment by asyasky** [comment]
The biggest time gap is immediately after this query (the query itself isn't flagged as long, but there's always a 1 second+ gap after it), so either this query takes a long time to return or there's slow processing happening on the server after it's returned.

SELECT [s].[ID], [s].[PuzzleID], [s].[ResponseID], [s].[SubmissionText], [s].[SubmitterID], [s].[TeamID], [s].[TeamID1], [s].[TimeSubmitted], [s.Puzzle].[ID], [s.Puzzle].[CustomURL], [s.Puzzle].[Description], [s.Puzzle].[EventID], [s.Puzzle].[Group], [s.Puzzle].[HintCoinsForSolve], [s.Puzzle].[HintsAreCumulative], [s.Puzzle].[IsCheatCode], [s.Puzzle].[IsFinalPuzzle], [s.Puzzle].[IsGloballyVisiblePrerequisite], [s.Puzzle].[IsMetaPuzzle], [s.Puzzle].[IsPuzzle], [s.Puzzle].[MaxAnnotationKey], [s.Puzzle].[MinPrerequisiteCount], [s.Puzzle].[MinutesOfEventLockout], [s.Puzzle].[MinutesToAutomaticallySolve], [s.Puzzle].[Name], [s.Puzzle].[OrderInGroup], [s.Puzzle].[PuzzleVersion], [s.Puzzle].[SolveValue], [s.Puzzle].[SupportEmailAlias], [s.Puzzle].[Token], [s.Response].[ID], [s.Response].[IsSolution], [s.Response].[Note], [s.Response].[PuzzleID], [s.Response].[ResponseText], [s.Response].[SubmittedText]
FROM [Submissions] AS [s]
INNER JOIN [Puzzles] AS [s.Puzzle] ON [s].[PuzzleID] = [s.Puzzle].[ID]
LEFT JOIN [Responses] AS [s.Response] ON [s].[ResponseID] = [s.Response].[ID]
WHERE ([s].[TeamID] = @__teamId_0) AND ([s.Response].[IsSolution] = 1)
ORDER BY [s.Puzzle].[Group]
