### ISSUE TITLE
Primary key violations on annotations

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#384]
We're seeing lots of SqlExceptions due to primary key violations on annotations

_MS.ProcessedByMetricExtractors: (Name:'Dependencies', Ver:'1.0')
Account Id: <undefined>
Application version: 1.0.0.0
AspNetCoreEnvironment: Production
Auth user Id: <undefined>
Base name: tcp:puzzlehunt.database.windows.net,1433 | puzzleserver
Browser version: <not collected>
City: Whittier
Client IP address: 0.0.0.0
Cloud role instance: RD0003FFE54529
Cloud role name: puzzlehunt
Country or region: United States
Dependency duration: 3 ms
Dependency Id: 4dafbbb47eef4426aea1ddf49f2b6e5b
Dependency name: SQL: tcp:puzzlehunt.database.windows.net,1433 | puzzleserver
Dependency type: SQL
Device model: <undefined>
Device type: PC
Event time: 4/7/2019, 4:56:54 PM
Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Annotations'. Cannot insert duplicate key in object 'dbo.Annotations'. The duplicate key value is (93, 1120, 249).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlExc...
Operating system: <not collected>
Operation Id: ca30a12e-4e18897735a39413
Operation name: POST Sync/Post [eventId/puzzleId]
Parent Id: ca30a12e-4e18897735a39413
Result code: 2627
Sample Rate: 25
SDK version: rdddsc:2.6.4-28401
Session Id: v0lsN
Source of synthetic traffic: <undefined>
State or province: California
Successful call: false
Telemetry type: dependency
User Id: ebTuT

<a href="https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/H4sIAAAAAAAAA1VQO2%2BDMBD%2BLzfjCoOBmDVDxdKhjTp0qc72JUEF2zKmj0T89xqFqOp63%2FO%2BK2hnY0AdXylMvbPQAocsXUfvLNnYGWiv8IQjJcTPl8tA59nGRHmZ1aRD72NSrSw4SkKsTcmQlGCCVMmkyA2rcSc4F6IpeJV0zzS5OWh6DG72%2F0zfwwmWDJyngHdXOw9DBvS5VQHTKKkbLlklZc44J8kwNxUjhRKV0FohwiY4oBrW2oY8WUNW9zQlLPYjTRHHNbzIk1UuWN4cirKt6rYSD7tavG20fRqHvuO9hkZ9pr9WgY4UAoV1ofjjU1SZgb1N9eXCRxdp7JLB6fYOLMsvQzlCIG8BAAA%3D/ComponentId/%7B%22Name%22%3A%22puzzlehunt%22%2C%22SubscriptionId%22%3A%22f9eaa6d3-aeb4-4eb3-940d-6a8411447215%22%2C%22ResourceGroup%22%3A%22puzzlehunt_rg%22%7D" target="_blank">View this instance in the Azure portal<\a>

**Comment by morganbr** [comment]
@jaylorch  FYI

**Comment by jaylorch** [comment]
Would this be reported even though I catch the exception?  If it's the exception I catch, it's perfectly benign.

**Comment by jaylorch** [comment]
Yeah, that's probably what's going on.  I see the documentation says:

Does my app definitely have a problem?
No, a notification doesn't mean that your app definitely has a problem. Although an excessive number of exceptions usually indicates an application issue, these exceptions might be benign and handled correctly by your application.
