### ISSUE TITLE
Require valid team PrimaryContactEmail and player Email

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#391]
Yes. Here's the regex I think we should validate against
`/[^@\s]+@[.A-Za-z0-9-]+(\s+[,;]\s+[^@\s]+@[.A-Za-z0-9-]+)/`.
There are lots of invalid email addresses this will match and this errs on the side of avoiding false negatives vs. avoiding false positives.

_Originally posted by @Vroo in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTY3NTg4ODc5OnYy/pull_request_review_threads/discussion_

**Comment by Vroo** [comment]
In case someone else gets there before me, here's the code in my local branch (in MailHelper)
```
    private static String VALID_EMAIL_PATTERN = "^\\s+[^@\\s]+@[.A-Za-z0-9-]+(\\s+[,;]\\s+[^@\\s]+@[.A-Za-z0-9-]+)\\s+$";

    /// <summary>
    /// Is the string a valid email or list of comma/semicolon-separated emails?
    /// Errs on the side of allowing false positives rather than having false negatives.
    /// </summary>
    public static bool IsValidEmail(string s)
    {
        return Regex.IsMatch(s, VALID_EMAIL_PATTERN);
    }
```

**Comment by tabascq** [comment]
Hi @Vroo , I have been trying to add this code, and the regex is rejecting all addresses I throw at it. I'm not the best at reading regex strings so I cannot tell what is wrong.

**Comment by tabascq** [comment]
I've tried my own personal email, no@no.no, etc. I also tried adding a comma and semicolon after.

**Comment by tabascq** [comment]
I'm going to switch over to the approach described in the first answer on this post, and I will make sure to accept comma and semicolon delimited lists.

https://stackoverflow.com/questions/5342375/regex-email-validation

**Comment by Vroo** [comment]
Stupid typos.
"\\s*[^@\\s]+@[.A-Za-z0-9-]+(\\s*[,;]\\s*[^@\\s]+@[.A-Za-z0-9-]+)*\\s*"

**Comment by tabascq** [comment]
OK thanks - but any objections to my letting .NET just figure it out for us?

**Comment by Vroo** [comment]
Whatever's easier.
