### ISSUE TITLE
Figure out why site.min.css isn't showing up

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#413]
Right now things that are in site.css/site.js aren't making it into site.min.css/site.min.js and are therefore not making it in to the deployed site. That means that we need to add inline styles/scripts to individual files which we don't want. The puzzle and team lists for authors/admins have this problem with shortcuts.

**Comment by jenetlan** [comment]
Updated to add that site.js is having the same issue as site.css

**Comment by philipzloh** [comment]
Fixed by #469
