### ISSUE TITLE
[P0] Adjust lockout times for DC puzzles

### ISSUE THREAD

**Issue by jenetlan** [PuzzleServer/mainpuzzleserver#453]
DC puzzles felt like they had overly-restrictive lockout times. We could adjust this with changes to the overall algorithm or we could look at adding a DC property to puzzles and having a DC-specific algorithm. (note: having the DC property for a puzzle would also let us display a reminder that the puzzle has DC on the submissions page and/or the play page)

**Comment by tabascq** [comment]
Fixed by #486
