### ISSUE TITLE
Add Auto-Refresh option for state map page

### ISSUE THREAD

**Issue by lambertwang** [PuzzleServer/mainpuzzleserver#500]

**Comment by tabascq** [comment]
Here is how the old site did it, not yet sure how this translates to Razor:

    public partial class AdminMaster : System.Web.UI.MasterPage
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // Automatically refresh pages based on query string
            if (!String.IsNullOrEmpty(this.Request.QueryString["Refresh"]))
            {
                HtmlMeta tag = new HtmlMeta();
                tag.HttpEquiv = "REFRESH";
                tag.Content = Convert.ToInt32(this.Request.QueryString["Refresh"]).ToString();
                this.Head.Controls.Add(tag);
            }
        }
    }

**Comment by morganbr** [comment]
Fixed in #503
