### ISSUE TITLE
Top level menus

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#53]
Provide a place for people to start making pages and hooking them up.

Strawman proposal follows.

[Note: ~ links only available when the event is running]
[Note: * links should work for authors AND for admins, just with a different puzzle set]
[Note: ! links are admins only]

NAME OF EVENT

Puzzles
  ~ Solved Puzzles
  ~ Unsolved Puzzles
  * Administer Puzzles
  * Import Puzzles/Responses (P2 but really really helpful)

N Updates (if any) (aka Tasks and response updates - look ma, no mailer)
  each update listed here in menu

Results
  ~ Standings
  ~ Fastest Solves
  * Puzzle State Map
  * Submissions
  * Puzzles in lockout

Registration
  My team (if known)
  Matchmaking Zone (teams ISO players, players ISO teams)
  List of Teams
  List of Players (full details for admins)
  ! Authors
  ! Admins

Resources
  FAQ
  Rules
  Encodings
  ! Event Properties
  My Events
  ! Events Dashboard

Sign up/Log in

**Comment by jenetlan** [comment]
https://github.com/PuzzleServer/mainpuzzleserver/pull/136
https://github.com/PuzzleServer/mainpuzzleserver/pull/143
https://github.com/PuzzleServer/mainpuzzleserver/pull/163

**Comment by jenetlan** [comment]
Done
