### ISSUE TITLE
Put a max length on team name and bio

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#585]

**Comment by asyasky** [comment]
Actually hit this with NIPD 2021, so we need to make sure this (and the identical team name bug) are fixed before the next event.

**Comment by jbodner09** [comment]
Partially addressed by #690.  Bio still needs to be limited, and we should double-check all other text input fields like feedback, answer submission, etc.

**Comment by jbodner09** [comment]
Closing in favor of #763
