### ISSUE TITLE
Web puzzles can be accessed via direct link even if user doesn't have permission (or without logging in)

### ISSUE THREAD

**Issue by Spartan97** [PuzzleServer/mainpuzzleserver#594]
Kirn sent me a link to her web puzzle to test (link redacted but it's on the puzzleserverteststore). I got access to it with no problem even though I shouldn't have access to that puzzle as an admin, author, or player. I even tried it in an incognito window and could access that puzzle without logging in.

Not a huge problem since the links are unguessable, but probably should be patched eventually.

**Comment by tabascq** [comment]
Was it a raw link? Raw links are open to all. The non-raw links are properly secured.

**Comment by tabascq** [comment]
Guessing it was the raw one since you mention it's against puzzleserverteststore...

**Comment by Spartan97** [comment]
Yeah it was the raw link -- so by-design? Is there any possibility that a player could send these raw links to another team that hasn't unlocked the puzzle yet? Not relevant for this event but the scenario is possible.

**Comment by tabascq** [comment]
Yes there is that possibility, but there is also the possibility that a player could outright give answers to another team, etc.

**Comment by Spartan97** [comment]
Makes sense to me
