### ISSUE TITLE
Add feedback link/form to answer submission page

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#676]
After a puzzle is completed, the answer submission page should link to the feedback page or include a feedback form inline to encourage submitting feedback. This should only be enabled for events that have feedback enabled.

**Comment by jbodner09** [comment]
I believe this was closed by #682

**Comment by vidapour** [comment]
Closed with #682

**Comment by vidapour** [comment]
Closed with #682
