### ISSUE TITLE
Ensure PuzzleStatePerTeam table integrity

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#68]
The PuzzleStatePerTeam table will be particularly sensitive to integrity issues since we don't want missing or duplicate entries. To handle this, we need a few things:
1. Required attributes on the Puzzle and Team entries. That will both avoid nulls and enable cascading deletes
2. A unique index on Puzzle+Team to prevent duplicate entries. We might want to make this the primary key.
3. Whenever a team is created, states for all puzzles must be generated and the reverse for puzzle creation. This should happen transactionally so that we don't lose some states if the request fails or is interrupted. 
 a. Ideally, this would also do transactional/locking reads such that a new team can't be created in the middle of puzzle creation or vice versa. It's not totally clear how to do that with EF or whether that's a significant concern for us since it's a fairly tight race condition.

**Comment by morganbr** [comment]
When this is fixed, also remove EnsurePuzzleStatePerTeamAsync from the status page since it shouldn't be creating the states.

**Comment by tabascq** [comment]
#70 is one implementation that is working, though I won't claim it is the best possible. Agree that transactional/locking would be better still.

**Comment by morganbr** [comment]
Fixed in #320
