### ISSUE TITLE
Feature request:  add the ability to filter out groups of puzzles from the state map

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#714]
This filtering should persist through a page refresh.  It would also be nice to be able to sort by groups too, so the metas for instance can be selected to always be to the very left.  

It would also also be nice to remove the excessive margin to the left of the page:  
![image](https://user-images.githubusercontent.com/30329717/177845665-a2effe3f-fa8b-4461-ab00-3759cc509d6b.png)

**Comment by tabascq** [comment]
Addressed by #716
