### ISSUE TITLE
Feature request: Improve UI for solving and submitting answers to puzzles

### ISSUE THREAD

**Issue by amgleitman** [PuzzleServer/mainpuzzleserver#719]
Several teams got confused about where to submit answers or check partial answers for data confirmation. They assumed that they could check their answers directly on the webified puzzles.

**Comment by jbodner09** [comment]
It sounds like the existing button that's just a link to the actual submission page isn't enough:  

![image](https://user-images.githubusercontent.com/30329717/179857154-6595a7ce-c0f0-4838-8cf7-0fcdbbf499d2.png)

Megan already created an API to enable the actual submission _box_ being directly on the puzzle page in a previous event (https://github.com/puzzleserver/mainpuzzleserver/blob/master/ServerCore/Pages/PuzzleApiController.cs), so it shouldn't be too hard to incorporate into future puzzle templates now that the webified puzzles are getting all the data necessary to call the API thanks to this year's changes.

**Comment by vidapour** [comment]
Streamline system of puzzlers seeing/solving puzzles and getting to the submit answers/see previous answer attemps/getting help/etc.

**Comment by jbodner09** [comment]
Closing since #817 provides an implementation that addresses this.
