### ISSUE TITLE
Feature request:  free agent system

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#721]
This will make the flow from creating an account in our system to signing up for an event to finding a team to play on much smoother.

**Comment by vidapour** [comment]
How to auto-team-ify our free agents? 
How to let interns choose between choosing a team to join vs letting us auto-assign them a team?
Do we want to combine this with merging function? Auto-merging?

**Comment by tabascq** [comment]
how to mark which teams are accepting random players so we can add one more person day-of?

**Comment by asyasky** [comment]
For teams that allow other players to join - add a setting for "I want to approve all new players" vs "just add anyone who needs a team."

**Comment by vidapour** [comment]
Team classification: competitive, intermediate, beginner, for fun
Team privacy: closed, open to applications, fully open
Free agent team matching: I'm feeling lucky -- do you want PD team to place you? if no -> pick my own team
Intern signup action: Create a team, Randomly assign me, I'll join myself

**Comment by morganbr** [comment]
Teams need to get a minimum number of MS employees

**Comment by morganbr** [comment]
Consider a lower than max auto-team size limit (e.g. once it has 10 players, make a new team even though 2 more would fit)

**Comment by morganbr** [comment]
Solution for minimum MS employees/interns: If there's a requirement on the event, only let people who meet the requirement use auto teams. (If there's no requirement, everyone can use them)
