### ISSUE TITLE
Navigation to the Team Composition Summary page fails

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#724]
Server responds with a 500 error

**Comment by jbodner09** [comment]
But only for pd2022; pd2021 is fine, so there's something about the list of teams in 2022 that's causing it.  I don't think it's any emoji since 2021 had plenty of those, so my next guess is just how many members a few teams have beyond the limit.

**Comment by tabascq** [comment]
Application Insights reports this as a NullReferenceException in TeamCompositionSummaryModel.MapToTeamComposition. Not sure how to narrow it down further just yet.

**Comment by tabascq** [comment]
Looks like we have a player on team "Tech taco" who has no email (@asyasky : any idea how this could happen?) and that is probably the source of the nullref, since MapToTeamComposition calls EndsWith on the email string.

**Comment by jbodner09** [comment]
I just started a PR to fix some trivial bugs (#725), and among other things, it's going to enforce that emails aren't empty, so at least in the future this shouldn't be possible.

**Comment by jbodner09** [comment]
Closing since #763 will prevent the state that caused this from happening in the first place.
