### ISSUE TITLE
Update external auth wiki with local development instructions

### ISSUE THREAD

**Issue by beckbria** [PuzzleServer/mainpuzzleserver#745]
I'm trying to get a local test environment running.  I read the [Local Dev Environment Setup](https://github.com/PuzzleServer/mainpuzzleserver/wiki/Local-Development-Environment-Setup) and [External Auth Setup](https://github.com/PuzzleServer/mainpuzzleserver/wiki/External-Authentication-Setup) documents, but I seem to be missing a step.  I've done some experimenting, and here's what I'd like to add to the External Authentication Setup:

```
The user secrets should contain the following values:

{
  "Authentication-Microsoft-ApplicationId": "<guid from Azure Console>",
  "Authentication-Microsoft-Password": "<client secret from Azure Console>"
}

To authorize a user login, you will need to create an Azure AD application.  Follow [the Azure AD guide](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) which will allow you to create an app. 

Once you do so:

1. Copy the Application (client) ID to the Authentication-Microsoft-ApplicationId secret
1. Create a client secret and copy its value (not its ID) to the Authentication-Microsoft-Password secret
1. Add http://localhost:44319/signin-microsoft as a supported Redirect URL for web applications
```

Defining those values in JSON allows the app to start (without them it fails saying that `Client Id is required`).  Creating a valid Azure app is required for the Login link to succeed, and the redirect URI is required for the request to not be rejected.

However, this is still not sufficient.  With these steps, attempts to log in locally fail with 

```
System.Exception: Correlation failed.`

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This is as far as I could debug tonight.  Am I overlooking a step (or a document) regarding how to set up a mock local environment?  All I really want to do is to test some [UI changes.](https://github.com/PuzzleServer/mainpuzzleserver/compare/master...beckbria:mainpuzzleserver:filter_link)

**Comment by tabascq** [comment]
Hi, did someone give you access to our Azure instance to get the guid and secret? I may be looking in the wrong place, but I'm not sure that you have the access needed for that step. You probably need to get one of us to mail you the guid and secret; for obvious reasons I can't post those in public. I don't have your email on file; send mail to tabascq, at hotmail.

**Comment by beckbria** [comment]
Thanks, talked offline and got those.  For future reference, the Correlation failed is caused by [SameSite cookie policy](https://stackoverflow.com/a/64874175) in Chrome.  Testing locally in Firefox works, as does adding the following to `Startup.Configure`:

```
            if (env.IsDevelopment())
            {
                app.UseCookiePolicy(new CookiePolicyOptions()
                {
                    MinimumSameSitePolicy = SameSiteMode.Lax
                });
            }
```

I'll file a separate bug to track adding that block of code.
