### ISSUE TITLE
Bug: Hidden puzzles shouldn't appear on correct answers page

### ISSUE THREAD

**Issue by asyasky** [PuzzleServer/mainpuzzleserver#754]
The list of correct answers shows hidden puzzles (timing puzzles are showing up at bottom of page).

**Comment by vidapour** [comment]
Teams/Answers -- Line 44 query

Kenny's working on it right now lol

Line 47: add "where state.Puzzle.IsPuzzle"

**Comment by vidapour** [comment]
Restructure query to start from submissions rather than puzzles
