### ISSUE TITLE
Bug: All Correct Answers page doesn't display the html module logos

### ISSUE THREAD

**Issue by asyasky** [PuzzleServer/mainpuzzleserver#755]
The All Correct Answers page has the html for the module logos but it doesn't work so it just looks broken. Ideally this should be working on this page, though removing the broken elements is also an option. See the puzzles list page for the working version. (PH 22 is the only event to use this so far, so need to look at that event to see this in action.)

**Comment by tabascq** [comment]
Fixed by #935 (forgot this was an existing issue at the time)
