### ISSUE TITLE
Puzzle tags for accessiblity

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#762]
Have a way to tag puzzles for whether they work with a screen reader or have other accessibility requirements/affordances

**Comment by jbodner09** [comment]
More generally, we've had this discussion before about how many "tags" a puzzle should have.  Should we surface the DC tag on the list of puzzles instead of just on the puzzle itself?  How about online-only puzzles?  Puzzles that, if you're going to print them, require color?  etc.

**Comment by vidapour** [comment]
Consider bringing up in overall PD meeting for design discussion.
