### ISSUE TITLE
Field lengths should be enforced in the database

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#763]
Followup to #725 since it originally was enforcing field lengths in javascript instead.

**Comment by Vroo** [comment]
IMHO, it's preferable to enforce field lengths in both the javascript and the back end so that appropriate error messages can be generated. Client-side enforcement prevents users from submitting invalid data. Server-side enforcement prevents users from hacking the browser to bypass the limits. Limits in the DB not enforced by either client or server code generate error messages that are unhelpful.

**Comment by jbodner09** [comment]
Per the comments on that PR, enforcement in the database apparently do also enforce in javascript, which is good enough for me.  I assume this is the documentation Morgan was referring to for the fields that need to be non-empty:  https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=net-7.0

**Comment by Vroo** [comment]
OK. I was responding to the first comment which said "instead" which isn't what you're actually doing.

**Comment by jbodner09** [comment]
Yeah, I'm taking out all of the field length stuff from that PR entirely just so there's less going on with it.

**Comment by jbodner09** [comment]
Field lengths from that PR:

ServerCore/Areas/Identity/Pages/Account/Edit.cshtml
	PuzzleUser.Email: 50
	PuzzleUser.Name: 50
	PuzzleUser.EmployeeAlias: 20
	PuzzleUser.PhoneNumber: 20
ServerCore/Areas/Identity/Pages/Account/Edit.cshtml.cs
	PuzzleUser.Email: >0
	PuzzleUser.Name: >0
ServerCore/Areas/Identity/Pages/Account/ExternalLogin.cshtml
	Input.Email: 50
	Input.Name: 50
	Input.EmployeeAlias: 20
	Input.PhoneNumber: 20
ServerCore/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml
	Input.Password: 50
ServerCore/Areas/Identity/Pages/Account/Manage/Index.cshtml
	Input.Email: 50
	Input.Name: 50
	Input.EmployeeAlias: 20
	Input.PhoneNumber: 20
ServerCore/Pages/Puzzles/SubmitFeedback.cshtml
	Feedback.WrittenFeedback: 500
ServerCore/Pages/Submissions/Index.cshtml
	Submissions.IndexModel.SubmissionText: 100
ServerCore/Pages/Swag/Register.cshtml
	Swag.LunchModifications: 500
ServerCore/Pages/Teams/Create.cshtml
	Team.Name: 50
	Team.RoomID: 20
	Team.CustomRoom: 20
	Team.PrimaryContactEmail: 50
	Team.PrimaryPhoneNumber: 20
	Team.SecondaryPhoneNumber: 20
	Team.Bio: 500
ServerCore/Pages/Teams/Edit.cshtml
	Team.Name: 50
	Team.RoomID: 20
	Team.CustomRoom: 20
	Team.PrimaryContactEmail: 50
	Team.PrimaryPhoneNumber: 20
	Team.SecondaryPhoneNumber: 20
	Team.Bio: 500

There are probably a few more that should be enforced in the database too that I missed here.

**Comment by tabascq** [comment]
The data model can be found in Data/DataModel.

When you're ready to update your local database, do this: https://github.com/PuzzleServer/mainpuzzleserver/wiki/Updating-the-DataModel-and-or-Database-Schema

**Comment by jbodner09** [comment]
Better summary of needed changes including ones not mentioned above:

In Feedback:

* WrittenFeedback needs max length = 500

In PuzzleUser:

* Name needs to be REQUIRED and max length = 50
* Email needs to be REQUIRED and max length = 50
* EmployeeAlias needs max length = 20
* PhoneNumber needs max length = 20
* TShirtSize needs max length = 5

in Response:

* SubmittedText (the public one) needs max length = 100 (since we're also constraining it in Submission)

in Submission

* SubmissionText (the public one) needs max length = 100
* UnformattedSubmissionText also needs max length = 100

in Swag

* LunchModifications needs max length = 100 (note that this is lower than what was specified above)
* ShirtSize needs max length = 5
(note that Lunch doesn't need constraint since it can only be set via radio buttons)

in Team

* Name needs max length = 50
* CustomRoom needs max length = 20
* PrimaryContactEmail needs to be REQUIRED and max length = 50
* PrimaryPhoneNumber needs max length = 20
* SecondaryPhoneNumber needs max length = 20
* Bio needs max length = 500
(note that RoomID doesn't need constrained because it's not a string)

Also, I believe we're good with the ASP.NET identity stuff.  It looks like the name/email/phone number/alias fields are actually the ones from PuzzleUser, so since they're constrained there, they shouldn't need anything extra in the auth pages!

**Comment by Vroo** [comment]
I will look at this. Also, allows strings consisting entirely of white space or emoji.

**Comment by jbodner09** [comment]
All emoji is fine, that's at least visible.  For that matter, "emoji" are just non-ASCII unicode characters, which need to be supported in case a team wants to, for example, have a Chinese name, which we've seen in the past, so there's no need to worry about that.  

All white space names should already trigger the "required" attributes (minus the ones that need to be added to the database), since user input is sent through an Is Null Or Whitespace check and only allowed to proceed if it's not.  Team names are already tagged properly with both the "required" attribute and a regex that requires them to start with a non-whitespace character, so it should just be the ones mentioned in my most recent comment above that don't have those tags yet.

**Comment by tabascq** [comment]
Agree on emoji, many teams like to use those and we shouldn't disallow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vroo** [comment]
I wasn't suggesting disallowing emoji. As new emoji are constantly being added, it's not uncommon for what one person enters as an emoji  to not show up to someone else. Requiring a name to contain at least one non-emoji character is a crude way of addressing that.

I will see if there's a way for me to match by Unicode version (not to disallow newer characters but to require at least one older well-supported character).

**Comment by tabascq** [comment]
Some teams prefer names that are just emojis, e.g. the teams in 70th and 73rd place at Teams (huntinality.com)<https://www.huntinality.com/teams>. I think it is a mistake to require a non-emoji character.
________________________________

**Comment by jbodner09** [comment]
I thought the whole point of Unicode was that it's THE standard.  And thanks to .NET, _we_ shouldn't have to do anything special to support it.  If somebody uses something super new, we should assume that even if it's not _currently_ supported by all browsers/OS's (since the underlying font rendering is often up to the OS), it will be eventually, since support does take time to roll out due to different companies having different update schedules.  

Unless you know of bugs we currently have around displaying Unicode, I'd say there's really nothing you need to worry about with emoji.  In fact, the only time I've ever had to make sure they're handled properly is when I did MANUAL text processing when I re-did the lunch script:  https://github.com/PuzzleServer/LiveEventScheduleGenerator/blob/main/Lunch-T-shirt-script/makePDFs.ps1

**Comment by Vroo** [comment]
Yes, Unicode is a standard but there are many versions of the standard. The current version is 15.1 and it's updated more frequently than fonts are. While manipulation of Unicode happens server-side, ***rendering*** of characters happens on the client side and if a name consists entirely of new characters it won't render unless the user has updated fonts. Here's an example of tolerable misrendering:. 🍋‍🟩. That should look like a lime but it will render as a lemon with a green square for many people. On the other hand, this character 🫛 might not render at all for some people as there's no fallback. These characters don't render for me  and they are all different valid Unicode characters.

Anyway my thought is to find out if it's possible to match against Unicode version and reject if names consist ***entirely*** of characters in a version of Unicode not yet widely supported.

Let me find out what's possible before you shoot this down.

**Comment by tabascq** [comment]
I am fine with some kind of cutoff in emoji support so long as (a) a name consisting purely of widely-supported emoji is OK and (b) we can advance the cutoff line in some reasonably straightforward manner going forwards as we determine that more emoji become widely supported.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
