### ISSUE TITLE
Write Author's guide to the site

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#764]
There are lots of features for authors, we should document them

**Comment by morganbr** [comment]
Possible topics include:
* Basics of puzzle addition/setup
* Groups
* Prereqs
* Responses
* Hints
* Timed unlocks
* Materials
* Custom URLs
* Errata
* Freeform
* Meta pieces
* Cheat codes
* Data confirmation
* Lockout puzzles
* Annotations

**Comment by tabascq** [comment]
Add:

- announcements
- homepage options

**Comment by digit01Wave** [comment]
@morganbr and @tabascq , I have written all the documents for the pieces that I know. There are a few I don't know that I have listed under https://github.com/PuzzleServer/mainpuzzleserver/wiki/Pending-pages

Either we need a session for you all to tell me what each of these things are or we can reassign this item
