### ISSUE TITLE
Use a lot less of @Html.DisplayFor

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#769]
Turns out that this is causing lots of runtime JITting, and removing this from the add-an-admin page turns the page load time from ~7s to ~1s.

We should do a systematic purge of this construct except for places where we actually use it. Those places should be places that have [Display....] attributes.

**Comment by tabascq** [comment]
Skip this for properties with attributes [DisplayFormat] or [Display]

**Comment by tabascq** [comment]
Also handle @Html.DisplayNameFor

**Comment by digit01Wave** [comment]
> Html.DisplayNameFor

@tabascq , for these, why can't we just hard code the name into the html rather than using the Html.DisplayNameFor? Is it just so that the display name change can be shown in one place?

**Comment by tabascq** [comment]
You can hardcode it - we'll lose a little flexibility, but we aren't using said flexibility.

**Comment by digit01Wave** [comment]
Ok. I will hardcode the Display but will leave display format
