### ISSUE TITLE
Revamp announcements

### ISSUE THREAD

**Issue by digit01Wave** [PuzzleServer/mainpuzzleserver#783]
Right now announcements look like this
https://github.com/PuzzleServer/mainpuzzleserver/wiki/Make-an-announcement

Ideally it won't require a refresh
Ideally it will pop into whatever bodner is doing on the iframe thing
Ideally it will pop and ding and sound
Ideally it won't be every player in the world at the same time
example: "you, building 8, you come down now"

**Comment by vidapour** [comment]
linked with #879
