### ISSUE TITLE
Add pizza support to site

### ISSUE THREAD

**Issue by asyasky** [PuzzleServer/mainpuzzleserver#789]
Requirement notes from PD meeting:
Pizza drop down (1 per 3 people, defaults to Unselected so we know who hasn't touched their options, one topping)
Ask remote vs in person @ registration & affects food drop down
If possible: notifications in the system for when pizza arrives
Backend output for ordering
Notification on site with deadline for ordering

**Comment by morganbr** [comment]
Need to be able to lock orders at a certain date

**Comment by morganbr** [comment]
If last person in a pizza bracket leaves, delete the last pizza. Ideally notify team they're losing a pizza.
Email on pizza changes so teams know what happened (add/remove/change by other team members)
Should be swag events only
Maybe include text making it clear you're making a choice with your team, don't be a jerk
Don't forget to include merging (whatever was ordered previously counts -- no limit on number)
Need to handle TeamMiscDataChanged date
Need to be able to calculate "unordered" pizzas -- if a team didn't specify, they get added to the pool of "buffer" pizzas. Include this in the admin report

**Comment by morganbr** [comment]
Sketch of flows 
![PizzaWhiteboard](https://github.com/PuzzleServer/mainpuzzleserver/assets/11641665/7024c1de-2ca5-407c-b655-4b86b203ff61)

**Comment by vidapour** [comment]
Consider https://github.com/PuzzleServer/mainpuzzleserver/issues/694 for V2

**Comment by vidapour** [comment]
closed by #802 and #809
