### ISSUE TITLE
Things still missing from SinglePlayerPuzzles

### ISSUE THREAD

**Issue by digit01Wave** [PuzzleServer/mainpuzzleserver#829]
- [DONE] Hints
- [DONE] Feedback
- [DONE] Remove from top if none available
- [DONE] Allow rename (not all SinglePlayerPuzzles are necessarily Pregame puzzles) 
- [DONE] Allow unlocking of puzzle for a specific player (instead of just for yourself)
- [DONE] Fastest solves page should at least show pregame puzzles for total solved (see josh's comment)

**Comment by jbodner09** [comment]
If an event has no single player puzzles, the link in the top bar should be hidden, especially since it causes it to expand to 2 lines before you've registered for a team.
