### ISSUE TITLE
Print embedded puzzles directly

### ISSUE THREAD

**Issue by tabascq** [PuzzleServer/mainpuzzleserver#832]
Too risky for right now and less necessary for this year's puzzles, but it should probably be possible to print a puzzle without needing to click a new link.

**Comment by jbodner09** [comment]
Yup, it should be easy to define some css for the embedding page to strip off the nav bar, copyright footer, answer box and previous submissions, etc.  and then printing from the embedding page will look good.

**Comment by tabascq** [comment]
People ran into this issue for our NYE event, would be nice to fix going forwards.

**Comment by jbodner09** [comment]
Will definitely be taken care of during the rest of the site refresh.
