### ISSUE TITLE
Single Player puzzles should not be part of the ripple unlock when Start the event is Solved

### ISSUE THREAD

**Issue by metapzl** [PuzzleServer/mainpuzzleserver#849]
Generally speaking this shouldn't just be for Start the event

Perhaps Team puzzles should ripple unlock only Team puzzles
and Single Player puzzles should ripple unlock only Single Player puzzles

**Comment by vidapour** [comment]
Currently site crashes if a 'start event' puzzle tries to unlock single-player puzzles
