### ISSUE TITLE
Puzzle autolock to facilitate testing

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#872]
Now that we have puzzle embedding, it would be really handy for alpha testing to record how many people have looked at a particular puzzle.  And if a certain number of people have opened a puzzle, or maybe a certain number of people keep it open for more than a minute, it should autolock for everybody else.  This is the equivalent of only printing a couple of copies for testing and when they're all taken, they're all taken.

**Comment by vidapour** [comment]
- puzzles in need of test solving could be on home page for easy access
- add 'claim' button so that testers can self-select which puzzles they want to solve, which locks puzzle
- needs an event property to turn this on

**Comment by Vroo** [comment]
I think locking puzzles as described here might be counterproductive. It's not uncommon for one person to start a puzzle and then put it down for other people to pick up. Locking the puzzle could frustrate that. And it might interfere with people solving in groups (which, as an author, I encourage).

If I interpret this correctly, what you are trying to solve is getting alpha solves or puzzle verification solves distributed so not everyone solves the same ones. If that's the case, I think a good solution would be to track solves. So, as a test solver, I can see how many other people have already solved a particular puzzle. You can then encourage people to work on the less-solved puzzles.

Also, tracking who is working on puzzles is potentially useful. Many teams already track this. Providing support for tracking in the server would then make that information available to authors, in case test solving teams don't track it or neglect to share it. On teams that I have been on, we track both who is working on a puzzle "right now" and who has worked on it in the past.

**Comment by tabascq** [comment]
closed in favor of alpha events
