### ISSUE TITLE
Add notification system

### ISSUE THREAD

**Issue by digit01Wave** [PuzzleServer/mainpuzzleserver#879]
Would be nice if we had notifications that pop up on the corner while players play.

Maybe even send an email whenever there is an notification

**Comment by vidapour** [comment]
1st iteration: bell tab
2nd iteration: fading banner

How does it know what to show:
- parallel with bulk mail blasts
- change [Event Mailer](https://puzzlehunt.azurewebsites.net/pd2023/admin/Events/Mailer/Players) page to 'Notifications' page -> for bulk and individual teams
