### ISSUE TITLE
Give authors an easy way to unlock a puzzle for all users

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#881]
We already have a button to unlock a puzzle for all users/teams, but it's hidden behind a puzzle's status page.  We should add a column to the author (and admin) puzzle list at https://puzzlehunt.azurewebsites.net/pdalpha/author/Puzzles with a button to unlock a specific puzzle for everybody.  This will help with the work for #872

**Comment by tabascq** [comment]
button to status page
