### ISSUE TITLE
Add a variety of oauth providers

### ISSUE THREAD

**Issue by tmathmeyer** [PuzzleServer/mainpuzzleserver#901]
Every time I sign up for a non-intern puzzleday, I have to create another throwaway microsoft account to use, since I don't have a personal one, and I don't bother keeping the credentials for more than a few days. Please consider adding additional oauth providers. I can help if you want.

**Comment by vidapour** [comment]
Jessica thinks you're a troll kthanksbai

**Comment by vidapour** [comment]
In all honesty, this would add a lot of complexity given the items we're planning to build, so we likely won't prioritize this in the near future.

We (minus Jessica) appreciate the input though!
