### ISSUE TITLE
Tracking issue for "I'm working on this puzzle!"

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#909]
Since the website now has support for realtime updates via Blazor and tracking state for puzzles thanks to embedding, now would be a good time to work on the "I'm working on this puzzle!" button so that remote teams have an easy way to track who's working on what.

**Comment by vidapour** [comment]
- tab is open marks puzzle as being 'worked on' by person X
- should have history of people who have opened tab, maybe have length of time each person was on? (might not be possible to show progress on webpage)

**Comment by Vroo** [comment]
Suggest green circle, yellow triangle, gray square for active, idle for <5 minutes, idle for >5 minutes. Color + shape works well for colorblind people.

**Comment by vidapour** [comment]
- cross btwn team status + google docs indicators

- team status indicator
- could track mouse/page/keyboard activity
- 'last active' state

- google docs contributor indicator
- use contributor initials to note where in the doc/puzzle they are
