### ISSUE TITLE
Ordered unlocking within groups

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#922]
Ability to set a puzzle to unlock once X other puzzles in its group have unlocked. Note: this may require making a table for groups (they're currently just a string in the Puzzles table).

**Comment by jbodner09** [comment]
Would a group table need to be a "group in event" table that's also keyed off of an event, so that each event only has access to the groups specific to it?

**Comment by tabascq** [comment]
Doing this without a table for now, if it's deemed grossly inefficient we can consider tweaking it later but I think it'll be fine as is.
