### ISSUE TITLE
Crash: Fastest Solves page in Author or Admin mode throws Key Not Found Exception

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#930]
![image](https://github.com/PuzzleServer/mainpuzzleserver/assets/30329717/ff392344-0bd0-4bbf-bde4-a294ca16d38b)

#908 is the likely culprit since it last touched the offending line.

**Comment by tabascq** [comment]
@digit01Wave wanna take a peek?

**Comment by digit01Wave** [comment]
Additional issue of not showing fastest solves if you didn't solve anything yet
![image](https://github.com/PuzzleServer/mainpuzzleserver/assets/4121745/08a5b71c-b566-4f4c-bf69-019d59818119)
