### ISSUE TITLE
Feature request:  file upload without obfuscated raw link

### ISSUE THREAD

**Issue by jbodner09** [PuzzleServer/mainpuzzleserver#934]
Currently, uploading files to the azure blob storage hides them behind an obfuscated link.  This makes it difficult to re-use files between events, and in the worst case forces us to upload resources for _puzzles_ to the repo that hosts the _website_.  For example, the css for styling puzzleday puzzles lives in the same folder as the css that styles the puzzleday homepage, which requires redeploying the entire website any time we need to make changes to puzzle styling.  

Even worse, when the puzzles are migrated to the nipd event, now they are all pointing to the outdated resources from the intern event, which in the worst case may no longer have permission to be accessed by the new event, causing all puzzles to need to be updated.  One possible solution for this (as discussed in #932) is to create an event-agnostic resource upload page on the website that will not hide uploaded files behind obfuscated links.  This will allow those links to be valid across any and all events.  

Besides the above use case of migrating puzzles between events, this will also help us no longer need to upload puzzle resources to the website repo, which I believe is very important since that means puzzle authors or creators won't need access to the website repo.  It also will help for hosting resources like Kenny's puzzlejs library, which is designed to be used by multiple events (barring versioning requirements).

**Comment by tabascq** [comment]
Handled by #936
