### ISSUE TITLE
Message feature requests

### ISSUE THREAD

**Issue by digit01Wave** [PuzzleServer/mainpuzzleserver#969]
- [DONE]Allow GC to filter to unclaimed messages only
- [DONE]Allow GC to filter to specific puzzle
- [DONE] Make chat boxes prettier
- [DONE]Respect event level flag that lets us hide help messages from GC if they are not the author
- [DONE] Don't allow users to post more messages after answers are released
- [DONE]Allow filter to only threads the author is explicitly on/supporting
- [DONE] Filter to unclaimed messages only
- [DONE] Live refresh

**Comment by tabascq** [comment]
During an event, Game Control is going to want to easily filter this down to unclaimed messages only.

Also, ideally GC will be able to see this page update live without needing to refresh.
