### ISSUE TITLE
"Login" button no longer looks like a button

### ISSUE THREAD

**Issue by sprx97** [PuzzleServer/mainpuzzleserver#971]
![image](https://github.com/PuzzleServer/mainpuzzleserver/assets/38958/e8d4f562-5ae0-4754-b2e0-11d850dddf26)

Unsure if this is intentional or not, but it's definitely off-putting.

To be clear the "bug" here is that the "Login" link at the bottom of my screenshot acts neither like a button nor like a hyperlink.

(Feel free to ping me here or on Discord if you have questions)
-- Jeremy

**Comment by jbodner09** [comment]
More bootstrap update shenanigans; will be fixed in #972 just because that PR is currently open
