### ISSUE TITLE
Allow hints+help threads

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#974]
We would like to allow hints for simple questions while still allowing help threads (at a cost of some hint tokens) at the same time

**Comment by digit01Wave** [comment]
@morganbr , do we want the number of hints to unlock messaging to be the same for each puzzle?

**Comment by digit01Wave** [comment]
The plan we're voting for is to have an event default value on the event object. Then a nullable override value on the puzzle object. That way the code can check for the override first & fall back to the event value if there isn't one.
